req_url : http://172.31.24.105:8007/dx-client-server/v2/api-docs?group=OB%E5%8C%85%E7%BD%91
module_path : client_server/report_app/
class_module_name : clientServerReportApp
module_desc_name : 信用盘后台
module_name : client_server
mark : client_server_report_app
sub_module_desc_name : 报表返佣返点模块
base_url_path :
tag_map : {
     返佣比例接口: commissionRate,
     返佣比例管理: dxSettlementCommissionProxyRecord,
     返点报表相关接口: rebateRateReport,
     返点比例接口: rebateRate,
     返点比例配置接口: rebateRateConfig,
     报表: report
}
