req_url : http://172.31.24.105:8008/dx-merchant-manager/v2/api-docs?group=10-%E7%B3%BB%E7%BB%9F
module_path : merchant_manager/system/
class_module_name : merchantManagerSystem
module_desc_name : 中控后台
module_name : merchant_manager
mark : merchant_manager_system
sub_module_desc_name : 系统模块
base_url_path : 
tag_map : {
     APP域名预埋配置: configDomain,
     参数字典: kvConfig,
     数据审计接口: dataAudit,
     枚举配置: enumConfig,
     滑动验证码: geetest,
     版本号配置: configAppVersion,
     登录记录: userLoginLog,
     管理员: admin,
     菜单管理: menu,
     角色权限: role,
     角色管理: systemRoleManage,
     账号管理: user
}