req_url: http://172.31.24.105:8008/dx-merchant-manager/v2/api-docs?group=4-%E4%BB%A3%E7%90%86
module_path: merchant_manager/proxy/
class_module_name: merchantManagerProxy
module_desc_name: 中控后台
module_name: merchant_manager
mark: merchant_manager
sub_module_desc_name: 代理模块
base_url_path:
tag_map: {
  专属域名管理: exclusiveDomain,
  代理借款账单: proxyLoanBill,
  代理列表管理: proxyList,
  代理备注: proxyRemark,
  代理层级配置: proxyLevel,
  代理登录日志: proxyLoginLog,
  代理相关: proxy,
  代理详情相关: proxyDetail,
  代理账户修改审核: updateProxyAudit,
  代理账户资料修改审核相关: proxyData,
  代理银行卡卡记录和代理虚拟币记录: bankProxyRecord,
  会员(代理)活动排除名单: activityMember,
  会员转代: memberTransfer,
  契约政策配置: minContract,
  契约模板配置: contract,
  契约管理配置: contractManage,
  推广图片管理: materialImage,
  推广域名管理: promoteDomain,
  新增代理&新增代理审核: newProxy,
  返佣比例接口: commissionRate,
  返点比例接口: rebateRate,
  返点比例配置接口: rebateRate
}
