req_url: http://172.31.24.105:8009/dx-proxy-manager/v2/api-docs
module_path: proxy_manager/
class_module_name: proxyManager
module_desc_name: 代理管理后台
module_name: proxy_manager
mark: proxy_manager
sub_module_desc_name: 后端接口
base_url_path: /dx-proxy-gateway
tag_map: {
  "业务报表-返点报表": report,
  "个人中心-个人资料": personalCenter,
  "个人中心-消息公告": personalCenter,
  "个人中心-返点比例": personalCenter,
  "二维码": common,
  "代理-基础接口": proxy,
  "代理-契约操作": proxy,
  "代理-推广图片素材": proxy,
  "代理-推广链接": proxy,
  "代理-数据概览": proxy,
  "代理-联系方式": proxy,
  "代理佣金": proxy,
  "代理佣金-收付记录": proxy,
  "代理俱乐部-基础接口": proxy,
  "代理借款账单": proxy,
  "代理列表-接口": proxy,
  "代理登录-接口": proxy,
  "代理盈亏": proxy,
  "代理管理后台-数据统计": proxy,
  "代理返点管理": proxy,
  "代用户存款取款记录": user,
  "会员代理备注": member,
  "会员列表": member,
  "会员备注": member,
  "会员报表": member,
  "会员模块-会员登录记录": member,
  "会员模块-用户管理": member,
  "会员盈亏报表": report,
  "会员管理-接口": member,
  "会员管理-游戏记录": member,
  "保险列表接口": insure,
  "俱乐部模块-新增俱乐部审核": clubAudit,
  "前端下拉框接口": common,
  "国际化测试接口": common,
  "枚举接口": common,
  "游戏管理": game,
  "滑动验证码": common,
  "牌桌管理": dxtable,
  "登录模块-获取验证码": login,
  "获取参数字典接口": common,
  "财务中心-上下分相关": finance,
  "财务中心-代理-提款相关": finance,
  "财务中心-代理-代下级存款相关": finance,
  "财务中心-代理-代理转账相关": finance,
  "财务中心-代理-额度充值相关": finance,
  "财务中心-代理充提记录": finance,
  "财务中心-代理添加银行卡管理": finance,
  "财务中心-代理账变记录接口-BW": finance,
  "财务中心-会员账单提现下分审核管理": finance,
  "财务中心-账变明细": finance,
  "返佣比例接口": commission,
  "返佣管理": commission,
  "返点比例接口": rebateRate,
  "返点比例配置接口": rebateRate,
  "通用接口": common,
  "钱包管理": wallet,
  "银行卡管理": bankManage,
  "会员账单提现下分审核记录--审核详情": memberWithdraw,
  "审核列表": memberWithdraw,
  "会员提现审核": memberWithdraw,
  "文件上传接口": common,
  "帮信用还款": helpCreditRepay
}
